version: "3.9"

volumes:
    datafiles:

services:

 db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # container_name: mysql8
    restart: always
    environment:
      environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: example
      # MYSQL_DATABASE: kmail
      
    volumes:
      - datafiles:/var/lib/mysql
    # restart: always
    ports:
      - 3306:3306

 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

 
 php:
   container_name: php7
   build : 
     context : . 
     dockerfile : Dockerfile
  #  environment:
  #     MYSQL_DBHOST: mysql
  #     MYSQL_DBPORT: 3306
  #     MYSQL_DBUSER : root
  #     MYSQL_DBPASS : secret
  #     MYSQL_DBNAME : kmail

   ports :
     - 80:80
   volumes : 
    - .:/var/www/html/
  #  depends_on : 
  #   - mysql

 
